In [2]:
import pandas as pd

reading the dataset

In [3]:
df=pd.read_csv("D:\people_wiki.csv")

In [4]:
df.head()

URI                 name  \
0        <http://dbpedia.org/resource/Digby_Morrell>        Digby Morrell   
1       <http://dbpedia.org/resource/Alfred_J._Lewy>       Alfred J. Lewy   
2        <http://dbpedia.org/resource/Harpdog_Brown>        Harpdog Brown   
3  <http://dbpedia.org/resource/Franz_Rottensteiner>  Franz Rottensteiner   
4               <http://dbpedia.org/resource/G-Enka>               G-Enka   

                                                text  
0  digby morrell born 10 october 1979 is a former...  
1  alfred j lewy aka sandy lewy graduated from un...  
2  harpdog brown is a singer and harmonica player...  
3  franz rottensteiner born in waidmannsfeld lowe...  
4  henry krvits born 30 december 1974 in tallinn ...

In [5]:
df.describe()

URI     name  \
count                                         59071    59071   
unique                                        59071    59070   
top     <http://dbpedia.org/resource/Digby_Morrell>  author)   
freq                                              1        2   

                                                     text  
count                                               59071  
unique                                              59071  
top     digby morrell born 10 october 1979 is a former...  
freq                                                    1

In [6]:
len(df)

59071

In [7]:
obama=df[df['name']=='Barack Obama']

In [8]:
obama

URI          name  \
35817  <http://dbpedia.org/resource/Barack_Obama>  Barack Obama   

                                                    text  
35817  barack hussein obama ii brk husen bm born augu...

In [9]:
print(obama['text'])

35817    barack hussein obama ii brk husen bm born augu...
Name: text, dtype: object


In [10]:
clooney=df[df['name']=='George Clooney']

In [11]:
clooney

URI            name  \
38514  <http://dbpedia.org/resource/George_Clooney>  George Clooney   

                                                    text  
38514  george timothy clooney born may 6 1961 is an a...

In [12]:
clooney['text']

38514    george timothy clooney born may 6 1961 is an a...
Name: text, dtype: object

for word count in a respective article

In [13]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
v=CountVectorizer()
o=v.fit_transform(obama['text'])

In [14]:
o

<1x270 sparse matrix of type '<class 'numpy.int64'>'
	with 270 stored elements in Compressed Sparse Row format>

oabama article word count

In [15]:
count=pd.DataFrame(o.toarray(),columns=v.get_feature_names())
count

13th  1961  1992  1996  1997  20  2000in  2004  2007  2008  ...  was  \
0     1     1     1     1     1   2       1     3     1     1  ...    5   

   where  whether  which  while  with  withdrawal  won  worked  years  
0      1        1      1      1     3           1    1       1      1  

[1 rows x 270 columns]

obama article word count in a sorted manner

In [16]:
count.T.sort_values(by=0,ascending=False)

0
the          40
in           30
and          21
of           18
to           14
...          ..
husen         1
hussein       1
ii            1
inaugurated   1
years         1

[270 rows x 1 columns]

to count the words in the clooney article

In [17]:
c=v.fit_transform(clooney['text'])

In [18]:
c

<1x236 sparse matrix of type '<class 'numpy.int64'>'
	with 236 stored elements in Compressed Sparse Row format>

In [19]:
count_clooney=pd.DataFrame(c.toarray(),columns=v.get_feature_names())

In [20]:
count_clooney

100  1960  1961  1978  1994  1997  1998  1999  2001  2004  ...  widened  \
0    1     1     1     1     1     1     1     2     1     1  ...        1   

   with  won  work  worked  working  world  would  writer  year  
0     4    1     2       1        1      2      1       1     1  

[1 rows x 236 columns]

In [21]:
count_clooney.T.sort_values(by=0,ascending=False).head()

0
the  35
and  15
in   14
of   14
for  13

In [22]:
count['obama']

0    9
Name: obama, dtype: int64

Using tf-idf to count the words in the corpus 

In [23]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer()

In [24]:
tfidf_matrix=tfidf.fit_transform(df.text.values)

In [51]:
name='Barack Obama'

In [60]:
row=df[df.name==name].index.tolist()[0]

In [56]:
features=tfidf.get_feature_names()

In [64]:
obama_matrix=pd.Series(tfidf_matrix.getrow(row).toarray().flatten(),index=features).sort_values(ascending=False)

obama article word count w.r.t. whole dataset

In [65]:
print(obama_matrix)

obama       0.365018
the         0.279323
act         0.249089
in          0.209673
iraq        0.151809
              ...   
equine      0.000000
equina      0.000000
equiluz     0.000000
equilium    0.000000
zzts        0.000000
Length: 548429, dtype: float64


In [27]:
from sklearn import linear_model
from sklearn import metrics
from sklearn.neighbors import NearestNeighbors

KNN model 

In [28]:
knn_neighbors=NearestNeighbors()

feature is used as the tf-idf matrix

In [29]:
knn_neighbors.fit(tfidf_matrix)

NearestNeighbors()

In [30]:
knn_neighbors.kneighbors(tfidf_matrix)

(array([[0.        , 1.01594537, 1.07258106, 1.08749884, 1.09243555],
        [0.        , 1.25111604, 1.26450119, 1.27857368, 1.2795241 ],
        [0.        , 1.10848393, 1.12016046, 1.12569541, 1.13546937],
        ...,
        [0.        , 1.21114464, 1.21151167, 1.21664395, 1.23411684],
        [0.        , 1.153835  , 1.16625693, 1.16833601, 1.16844735],
        [0.        , 1.21675471, 1.21693977, 1.21801618, 1.21887715]]),
 array([[    0, 32472, 36597,  1347, 40090],
        [    1,  8816, 54960, 49140, 39383],
        [    2, 48610,  4406, 16916, 54170],
        ...,
        [59068, 31151, 30706, 19782, 46886],
        [59069, 47859,  7191,  8745, 46525],
        [59070, 21896,  3790, 19105,  3260]], dtype=int64))

Finding the close neighbours 

In [67]:
close_friends=knn_neighbors.kneighbors(tfidf_matrix.getrow(row),return_distance=True)

In [69]:
names_index = close_friends[1][0]
names = [df.iloc[row]['name'] for row in names_index]
distances = close_friends[0][0]

giving the close friends names and the distances

In [70]:
print(names,distances)

['Barack Obama', 'Joe Biden', 'Hillary Rodham Clinton', 'Samantha Power', 'Eric Stern (politician)'] [0.         1.06843875 1.1098956  1.11802815 1.13996938]


Elton John Assignment

In [82]:
name='Elton John'
row=df[df.name==name].index.tolist()[0]
features=tfidf.get_feature_names()
elton_matrix=pd.Series(tfidf_matrix.getrow(row).toarray().flatten(),index=features).sort_values(ascending=False)
print(elton_matrix)

the          0.243684
billboard    0.192207
john         0.188958
elton        0.184686
furnish      0.181221
               ...   
equinix      0.000000
equines      0.000000
equine       0.000000
equina       0.000000
zzts         0.000000
Length: 548429, dtype: float64


In [83]:
close_friends=knn_neighbors.kneighbors(tfidf_matrix.getrow(row),return_distance=True)

In [84]:
names_index = close_friends[1][0]
names = [df.iloc[row]['name'] for row in names_index]
distances = close_friends[0][0]
print(names,distances)

['Elton John', 'Rod Stewart', 'Phil Collins', 'Adele', 'Sting (musician)'] [0.         1.08568969 1.12575123 1.12829458 1.13348797]


New model but with the raw_count of words of the dataset

In [87]:
vectorizer=CountVectorizer()

In [88]:
raw_count=vectorizer.fit_transform(df.text.values)

In [85]:
model=NearestNeighbors()

In [89]:
model.fit(raw_count)

NearestNeighbors()

In [90]:
model.kneighbors(raw_count)

(array([[ 0.        , 18.27566688, 19.10497317, 19.18332609, 19.49358869],
        [ 0.        , 21.81742423, 21.9089023 , 22.13594362, 22.13594362],
        [ 0.        , 21.11871208, 21.28379665, 21.33072901, 21.3541565 ],
        ...,
        [ 0.        , 20.19900988, 20.42057786, 20.42057786, 20.51828453],
        [ 0.        , 19.5192213 , 20.34698995, 20.71231518, 20.85665361],
        [ 0.        , 19.94993734, 20.04993766, 20.0748599 , 20.174241  ]]),
 array([[    0, 32472,  8758, 36597, 32924],
        [    1, 47762, 19534,  5784,  5649],
        [    2,  1438, 28498, 48198, 29744],
        ...,
        [59068, 19074,  9144,  1120, 23700],
        [59069, 24229, 45446,  5131, 26320],
        [59070, 42616, 35996, 39162, 57857]], dtype=int64))

Victoria Beckham Assignment

In [101]:
name='Victoria Beckham'
row=df[df.name==name].index.tolist()[0]
count_victoria=pd.Series(raw_count.getrow(row).toarray().flatten(),index=vectorizer.get_feature_names()).sort_values(ascending=False)

In [102]:
print(count_victoria)

the                 19
and                 12
in                  12
beckham              8
to                   6
                    ..
equiano              0
equestrienne         0
equestrianthemed     0
equestriansshe       0
zzts                 0
Length: 548429, dtype: int64


In [103]:
close_friends=model.kneighbors(raw_count.getrow(row),return_distance=True)

In [104]:
names_index = close_friends[1][0]
names = [df.iloc[row]['name'] for row in names_index]
distances = close_friends[0][0]
print(names,distances)

['Victoria Beckham', 'Kelly Bell', 'Rhian Samuel', 'Rikke Karlsson', 'Marie Brassard'] [ 0.         22.53885534 23.36664289 23.36664289 23.38803113]
